dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

jdk: openjdk8

cache:
  directories:
    - $HOME/.cache/bazel
    - $HOME/.cache/apt

before_install:
  - echo "s:======================================"
  - echo "Downloading bazel"
  - wget https://github.com/bazelbuild/bazel/releases/download/3.4.1/bazel_3.4.1-linux-x86_64.deb
  - sha256sum -c tools/bazel_3.4.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_3.4.1-linux-x86_64.deb
  - |
    exist() {
        [ -e "$1" ]
    }
  - |
    if exist $HOME/.cache/apt/*.deb
    then
        sudo mv $HOME/.cache/apt/*.deb /var/cache/apt/archives/
    fi
  - echo "Installing C++ and Python"
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends --no-install-suggests g++ python-dev python-pip python3-dev python3-pip maven libnuma-dev libc-dev openmpi-bin libopenmpi-dev
  - cp /var/cache/apt/archives/*.deb $HOME/.cache/apt/

jobs:
  include:
    - stage: "Build Stages"
      script:
        - bazel build --config=ubuntu twister2/... --action_env=JAVA_HOME
        - bazel test --config=ubuntu twister2/... --action_env=JAVA_HOME
      name: "Build & Test"
    - script:
        - bazel build --config=ubuntu //scripts/package:tarpkgs --action_env=JAVA_HOME
      name: "Tar Package"
    - script:
        - sh util/mvn/install-local-snapshot.sh
      name: "Maven Package"

notifications:
  slack:
    rooms:
      - dsc-twister:8iGGrATeSkL31CU3X9WQBNQV#build
