################################################################################
# Client configuration parameters for submission of twister2 jobs
################################################################################

# twister2 job name
twister2.job.name: "basic-kubernetes"

# number of CPUs for this job
twister2.cpu_per_container: "1"

# amount of memory for each CPU in bytes, 1GB=1024*1024*1024
twister2.ram_per_container: "1024"

# amount of hard disk space on each CPU in bytes, 1GB=1024*1024*1024
twister2.disk_per_container: "1024"

# number of worker instances
twister2.number_of_containers: "12"

# number of containers per pod
# default is 1
# number_of_containers must be divisible by containers_per_pod
kubernetes.containers_per_pod: "3"

########################################################################
# persistent volume related settings
########################################################################
# Do workers request persistent volume? it could be true or false
persistent.volume.requested: "true"

# Do workers request persistent logging? it could be true or false
persistent.logging.requested: "true"

# it could be "system" or "kubernetes"
# system logging puts less load on the kubernetes master but it may not show some logs from startup
# kubernetes logging gets the log messages from kubernetes master but it is more complete
persistent.logging.type: "system"

# nfs server address
nfs.server.address: "149.165.150.81"

# nfs server path
nfs.server.path: "/nfs/shared"

# worker persistent volume size
persistent.volume.per.worker: "1Gi"

# total persistent volume size for all workers in this job
# must be equal or higher than the total of all worker persistent volume sizes
persistent.volume.total: "100Gi"

# the admin should provide a PersistentVolume object with the following storage class. 
# Default storage class name is "twister2".
kubernetes.persistent.storage.class: "twister2"

# persistent storage access mode. 
# It shows the access mode for workers to access the shared persistent storage.
# if it is "ReadWriteMany", many workers can read and write
# other alternatives: "ReadWriteOnce", "ReadOnlyMany"
# https://kubernetes.io/docs/concepts/storage/persistent-volumes
kubernetes.storage.access.mode: "ReadWriteMany"

# what happens to the storage after the job has finished
# the storage can be retained (Retain), or deleted (Delete)
# default value is "Retain"
kubernetes.storage.reclaim.policy: "Retain"

