# This is the Headless Service object that is sent to Kubernetes master 
# when creating a job without external services

apiVersion: v1
kind: Service
metadata:
  name: <job-id>
  namespace: <kubernetes.namespace>
  labels:
    app: twister2
    t2-job: <job-id>
spec:
  clusterIP: None
  selector:
    t2-wp: <job-id>

