# a sample StatefulSet YAML file to create the Twister Job Master
# before creating this StatefulSet,
#   a Service needs to be created for this twister2 job master
#   then a PersistentVolumeClaim (if persistent storage is requested)
# need to be created.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: <job-id>-jm
  namespace: <kubernetes.namespace>
  labels:
    app: twister2
    t2-job: <job-id>
    t2-mss: <job-id>
spec:
  replicas: 1
  serviceName: <job-id>-jm

  selector:
    matchLabels:
      t2-mp: <job-id>

  template:
    metadata:
      labels:
        app: twister2
        t2-job: <job-id>
        t2-mp: <job-id>

    spec:
      terminationGracePeriodSeconds: 0
      volumes:
      - emptyDir:
          sizeLimit: <twister2.job.master.volatile.volume.size> + <Gi>
        name: twister2-volatile-dir
      - name: persistent-volume
        persistentVolumeClaim:
          claimName: twister2-storage-<job-name>

      containers:
        name: twister2-job-master
        image: twister2/twister2-k8s:<version>
        imagePullPolicy: <kubernetes.image.pull.policy>
        ports:
          name: job-master-port
          containerPort: <twister2.job.master.port>
          protocol: TCP
        resources:
          requests:
            cpu: <twister2.job.master.cpu>
            memory: <twister2.job.master.ram> + "Mi"
        volumeMounts:
        - mountPath: /twister2-volatile
          name: twister2-volatile-dir
        - name: persistent-volume
          mountPath: /persistent
        env:
          # below values are sample values.
          # they are calculated for each job
        - name: twister2.job.master.ip
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: twister2.job.master.port
          value: <twister2.job.master.port>
        - name: JOB_NAME
          value: <twister2.job.name>
        - name: kubernetes.namespace
          value: <kubernetes.namespace>
        - name: twister2.job.master.persistent.volume.size
          value: <twister2.job.master.persistent.volume.size>
        - name: twister2.worker.instances
          value: <twister2.worker.instances>

