###################################################################
# Twister2 Job Master related settings
###################################################################
# by default we are setting this to false for slurm as we are only supporting MPI at the moment
twister2.job.master.used: false

###################################################################
# Dashboard related settings
###################################################################

# Dashboard server host address and port
# if this parameter is not specified, then job master will not try to connect to Dashboard
# twister2.dashboard.host: "http://localhost:8080"
