# working directory
twister2.resource.scheduler.mpi.working.directory: "${HOME}/.twister2/jobs"

# mode of the mpi scheduler
twsiter2.resource.scheduler.mpi.mode: "slurm"

# the job id file
twister2.resource.scheduler.mpi.job.id: ""

# slurm script to run
twister2.resource.scheduler.mpi.shell.script: "mpi.sh"

# slurm partition
twister2.resource.scheduler.slurm.partition: "juliet"

# the mpirun command location
twister2.resource.scheduler.mpi.home: ""

# the package uri
twister2.resource.system.package.uri: "${TWISTER2_DIST}/twister2-core-0.6.0-SNAPSHOT.tar.gz"

# the launcher class
twister2.resource.class.launcher: "edu.iu.dsc.tws.rsched.schedulers.standalone.MPILauncher"


# mpi run file, this assumes a mpirun that is shipped with the product
# change this to just mpirun if you are using a system wide installation of OpenMPI
# or complete path of OpenMPI in case you have something custom
twister2.resource.scheduler.mpi.mpirun.file: "twister2-core/ompi/bin/mpirun"

# the uploader directory
twister2.resource.uploader.directory: "${HOME}/.twister2/repository"

# the uplaoder class
twister2.resource.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.localfs.LocalFileSystemUploader"

# this is the method that workers use to download the core and job packages
# it could be  HTTP, HDFS, ..
twister2.resource.uploader.download.method: "HTTP"