# Enable or disable checkpointing
twister2.checkpointing.enable: false

# persistent storage type
# could be: hdfs, nfs, local
# by default, it is local
twister2.persistent.storage.type: hdfs

# persistent storage root
# a directory with jobID is created under this directory
# all persistent storage related files are stored under that directory for the job
# for hdfs, it can be something like:
twister2.persistent.storage.root: "/twister2/"
# for nfs or local, it can be something like
# twister2.persistent.storage.root: "${HOME}/.twister2/jobs/"

# Source triggering frequency
# in milliseconds
# twister2.checkpointing.source.frequency: 1000

# Checkpointing message request timeout
# in seconds
# twister2.checkpointing.request.timeout: 600

###################################################################
# Fault Tolerance configurations
###################################################################

# a timeout value to determine whether a worker failed
# If a worker does not send heartbeat messages for this duration in milli seconds,
# It is assumed failed
# by default it is 10 seconds
# twister2.fault.tolerance.failure.timeout: 10000

# maximum number of times to re-execute IWorker after some other workers failed in the job
# default value is 5
# twister2.fault.tolerance.max.reexecutes: 5

# maximum number of times to re-start a worker from JVM
# default value is 5
# twister2.fault.tolerance.max.worker.restarts: 5

# maximum number of times to re-start mpi jobs in case of failures
# default value is 1
# twister2.fault.tolerance.max.mpijob.restarts: 1
